/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tfecw' at '3/31/17 9:06 PM' with Gradle 2.10
 *
 * @author tfecw, @date 3/31/17 9:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
